#!/usr/bin/perl

use POSIX;
use XML::Parser;

$minlat = 7.6230;
$minlon = -11.2217;
$maxlat = 9.7201;
$maxlon = -9.1661;

sub handle_start {
	my ($expat, $element, @tags) = @_;
	my %tags = @tags;

	if ($element eq "node") {
		$lat = $tags{'lat'};
		$lon = $tags{'lon'};

		if ($lat >= $minlat && $lat <= $maxlat && $lon >= $minlon && $lon <= $maxlon) {
			$lat{$tags{'id'}} = $lat;
			$lon{$tags{'id'}} = $lon;
		}
	}

	if ($element eq "way") {
		@nd = ();
	}

	if ($element eq "nd") {
		push @nd, $tags{'ref'};
	}
}

sub handle_end {
	my ($expat, $element) = @_;

	if ($element eq "way") {
		@lat = ();
		@lon = ();

		for $n (@nd) {
			if (defined($lat{$n})) {
				push @lat, $lat{$n};
				push @lon, $lon{$n};
			} else {
				push @lat, 0;
				push @lon, 0;
			}
		}

		for ($i = 0; $i < $#lat; $i++) {
			if ($lat[$i] != 0 && $lat[$i + 1] != 0) {
				print "$lat[$i],$lon[$i] $lat[$i + 1],$lon[$i + 1]\n";
			}
		}
	}
}

for $file (<*.osc.gz>) {
	print STDERR "$file\n";

	$parser = new XML::Parser(Handlers => { Start => \&handle_start, End => \&handle_end, });

	open(IN, "zcat $file |");
	$parser->parse(*IN);
	close(IN);
}
